### ISSUE TITLE
Is this repo still being developed?

### ISSUE THREAD

**Issue by schungx** [rhaiscript/vscode-rhai#1]
Any interest to move it into the rhai org?

**Comment by oovm** [comment]
Due to work reasons, I have not been able to maintain open source projects recently and for a long time to come.

I am willing to transfer the project.

I tried to transfer, but github says `You don’t have the permission to create public repositories on rhaiscript`

**Comment by schungx** [comment]
I've sent invitation to you for the rhai org.  Please see if you can transfer the repo now...

To keep naming consistent, I suggest naming it `rhai-vscode`?  Or is there some naming convention that we should follow?

**Comment by oovm** [comment]
The name is not important, it is up to you.

Most of the functions of the plugin should be implemented by lsp, so as long as js part is only responsible for the installation and update of lsp.

The developer can use `cargo install --debug`, because his cargo path must be in `PATH`, and vscode should first load the lsp executable file under this path.

The user needs to download the executable file of rhai to the same directory, because rhai must be in `PATH` in this case.

**Comment by schungx** [comment]
I am content just to have a reasonable syntax highlighter working... Small steps one at a time...  I haven't done anything with an lsp so it would have to be someone else who implements it...

**Comment by schungx** [comment]
@oovm   I've created a new publisher in `marketplace.visualstudio.com` called `rhaiscript` and published an updated version of the extension there under version `0.5.0`.

I would like to add you to the publisher as well, but it asks me for your email address...

Do you know how in visualstudio.com I can find your user ID and just add you to the owners list?
